### ISSUE TITLE
Rewrite CryptoModule

### ISSUE THREAD

**Issue by theScrabi** [CoraLibre/CoraLibre-android-sdk#1]
The [CryptoModule](https://github.com/theScrabi/CoraLibre-android-sdk/blob/master/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto/CryptoModule.java) and all the corresponding [Unit Tests](https://github.com/theScrabi/CoraLibre-android-sdk/blob/master/dp3t-sdk/sdk/src/androidTest/java/org/dpppt/android/sdk/internal/crypto/CryptoTest.java) need to be updated to PPCP. 
I recommend writing the Module from the ground up aside the original Module so existing code does not brake.

**Comment by BjoernPetersen** [comment]
Since this issue has been moved to "Done", can it be closed?
