### ISSUE TITLE
What's the time schedule, how long will it take?

### ISSUE THREAD

**Issue by realpixelcode** [CoraLibre/CoraLibre-android-sdk#12]
How much is already done, how much is still missing, how long will it take roughly? It would be great if an estimated time schedule could be published e.g. on the CoraLibe website. I don't want to rush anyone, I just want to know what the current progress is. Thanks for your work!

**Comment by theScrabi** [comment]
At the current rate we are getting forward I don't even know if we are getting ready at all, unless more people work on this project.

**Comment by realpixelcode** [comment]
I wish I could help, but unfortunately I don't know anything about this area 😕 Nevertheless I wish you all the best!

**Comment by theScrabi** [comment]
thank you :)
