### ISSUE TITLE
Enable issue tracker on CoraLibre-android for issues specific to the fork

### ISSUE THREAD

**Issue by BjoernPetersen** [CoraLibre/CoraLibre-android-sdk#16]
I think enabling the issue tracker in the app project would be helpful for collaboration and general approachability of the project.

**Comment by theScrabi** [comment]
What do you mean? The canban board?
https://github.com/CoraLibre/CoraLibre-android-sdk/projects/1

**Comment by theScrabi** [comment]
[done](https://github.com/CoraLibre/CoraLibre-android/issues)
