### ISSUE TITLE
Enable Kotlin support

### ISSUE THREAD

**Issue by BjoernPetersen** [CoraLibre/CoraLibre-android-sdk#18]
Kotlin is the first choice for new Android projects and offers quite a few quality-of-life improvements. I think we should transition the project to Kotlin to make it more attractive to new developers.

If others agree with me on this, I'd be glad to update the Gradle config myself.

### Pros

- A lot of nice language features
- Less prone to nullability bugs
- Full Java interoperability
  - Transition can be done one file at a time

### Cons

- Kotlin standard library dependency
- (A little) extra effort to keep the API usable for Java clients

**Comment by theScrabi** [comment]
I'd like to switch to kotlin, but I think we should do this later in a re factoring round. Rather than doing it now while trying to get basic functionality working. What do you think?

**Comment by BjoernPetersen** [comment]
Originally I thought it would be a good idea to gradually switch to Kotlin, i.e. write new files in Kotlin and convert only the existing files you're working on. Now I doubt that would be a good idea because mixing Kotlin conversion and work on features would make for some horrible diffs.

So let's go with your plan and do a big refactoring later. 👍
