### ISSUE TITLE
Implement Mockup Frontend API

### ISSUE THREAD

**Issue by theScrabi** [CoraLibre/CoraLibre-android-sdk#2]
Implement the highlevel API that should be used as a Mockup. This way tests with the frontend can already be conducted although its not yet functional. The inerface in question is described [here](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf). It is used by the App mostly in the [InternalExposureNotificationClient](https://github.com/theScrabi/CoraLibre-android/blob/master/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/InternalExposureNotificationClient.kt) class.

**Comment by haitrec** [comment]
Working on it
