### ISSUE TITLE
Implementation of exposure risk calculating algorithm

### ISSUE THREAD

**Issue by theScrabi** [CoraLibre/CoraLibre-android-sdk#20]
This module is completely missing so far. We didn't yet start to implement the algorithm that calculates the probability and risc factor of an exposure. By now we can only tell weather we saw an infected key or not.

Webpage descirbing the algorithm:
https://github.com/CoraLibre/CoraLibre-android-sdk/issues/16

Also you can take a look at it here:
https://github.com/corona-warn-app/cwa-app-android/issues/75#issuecomment-649665349

**Comment by Stypox** [comment]
I would like to take this, but I have no familiarity with the repo. Could you please point me to the place where we currently decide whether we saw an infected key or not?

**Comment by Stypox** [comment]
Webpage descirbing the algorithm:
#16

What does `#16` link to?

**Comment by Stypox** [comment]
Also here from Google:
- https://developers.google.com/android/exposure-notifications/exposure-notifications-api#exposureconfiguration
- https://developers.google.com/android/exposure-notifications/exposure-notifications-api#exposuresummary

**Comment by Stypox** [comment]
In the CWA app the ExposureConfiguration with all the parameters to feed to the algorithm is downloaded [here](https://github.com/corona-warn-app/cwa-app-android/blob/b03bb21197185ebe2539057a726ac51454d09164/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt#L110), but this is not something that should be handled in the sdk

**Comment by theScrabi** [comment]
As long as I know we get the parameters supplied from the app through the API which we expose to the app. @haitrec is that right?

**Comment by Stypox** [comment]
Shall the algorithm take as the parameter an object of the still-unmerged [IntervalOfCapturedData](https://github.com/CoraLibre/CoraLibre-android-sdk/pull/14/files#diff-e43bef4bdecb7739b10e0f99c3337749)? Theoretically it has all of the data needed for the calculation: the average rssi/attenuation can be calculated, the exposure date can be taken from the last object in the [CapturedData](https://github.com/CoraLibre/CoraLibre-android-sdk/pull/14/files#diff-bba072d43849541d626cb22fd1517601) list, and the exposure time is just the number of [CapturedData](https://github.com/CoraLibre/CoraLibre-android-sdk/pull/14/files#diff-bba072d43849541d626cb22fd1517601)s multiplied by 5 minutes. Correct me if I'm wrong ;-)

**Comment by theScrabi** [comment]
In my understanding you are right. We already provide all necessary information. All other things can be calculated based on what we provide.

Should I merge it now so you can use it, or would you use a dummy as long as bluetooth stack is not part of master yet?

**Comment by theScrabi** [comment]
This got done by https://github.com/CoraLibre/CoraLibre-android-sdk/pull/24. Is this a sufficient implementation?
