### ISSUE TITLE
Replace Bouncycastle

### ISSUE THREAD

**Issue by BjoernPetersen** [CoraLibre/CoraLibre-android-sdk#23]
Bouncycastle is only partially supported by Android. In its function as a Java Security Provider, it should be replaced by [conscrypt](https://github.com/google/conscrypt). 

As far as I can tell, Bouncycastle is only ever explicitly used for its HKDF implementation right now, which isn't part of the Java Cryptography Architecture and therefore not included in conscrypt. Bouncycastle is however a massive dependency just for HKDF, so I suggest using [Tink](https://github.com/google/tink) for HKDF, as it's actually already a transitive dependency through the `androidx.security:security-crypto` library.

If you agree with changing this, I'd be happy to implement it.

**Comment by theScrabi** [comment]
Yes please change it.
