### ISSUE TITLE
Strip non Bluetooth part

### ISSUE THREAD

**Issue by theScrabi** [CoraLibre/CoraLibre-android-sdk#4]
DP-3T apparently also Defines also a protocol to communicate with a server providing the keys of infected people. We don't need this as we only need he bluetooth part. Therefore all the cloud connection parts can be striped from the sdk.

**Comment by BjoernPetersen** [comment]
I'd like to claim this issue.

**Comment by theScrabi** [comment]
All right looking forward :)

Keep in mind you will not need any of the stuff that is comunicating with any server (protobuff for example). However leave the gatt part, also maybe crypto.

**Comment by BjoernPetersen** [comment]
We still need the protobuf dependency for implementing the Expose Notification API, don't we?

I'll focus on the actual backend part and maybe leave some bits and pieces that I deem to be helpful later.

**Comment by theScrabi** [comment]
The bluetooth advertisement part does not utilize protobuf. I don't know the api that is talking to the app, but I think it does not use protobuf either. Probably the communication with the servers utilize it, but that's not our concern as this is done in the frontend.

**Comment by BjoernPetersen** [comment]
As far as I understand from the [Exposure Notification API docs](https://developers.google.com/android/exposure-notifications/exposure-key-file-format) we'll receive a list of Protobuf files in the `provideDiagnosisKeys()` method, which we'll have to decode on our end.

**Comment by theScrabi** [comment]
Ah alight then.
