### ISSUE TITLE
Remove unused/old code

### ISSUE THREAD

**Issue by haitrec** [CoraLibre/CoraLibre-android-sdk#49]
Can we remove some of the (old) classes?

In particular:

- internal.crypto.CryptoModule with tests
- the other classes in internal.crypto (not internal.crypto.ppcp)
- the classes in internal.misc
- internal.bluetooth.BleCompat

related to https://github.com/CoraLibre/CoraLibre-android-sdk/pull/50

**Comment by theScrabi** [comment]
I think yes to all
