### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by theScrabi** [CoraLibre/CoraLibre-android-sdk#54]
- [x] create documentation repository
- [x] write functioning mkdocs site

**Comment by theScrabi** [comment]
I've created the repository: https://github.com/CoraLibre/documentation
Also I gave @Stypox @BjoernPetersen and @haitrec maintain access.

**Comment by haitrec** [comment]
I created an mkdocs site and filled it with some life:
https://coralibre.github.io/documentation/
